spring.application.name=transaction

# Aes
aes.secret-key = 12345678901234567890123456789012


# H2
spring.datasource.url=jdbc:h2:mem:transactiondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console